custom_imports: [projects.MTR.mtr]

work_dir: .
start_epoch: 0
max_epoch: 30
ckpt_save_interval: 5
log_iter_interval: 50

grad_norm_clip: 1000.0

dataset:
  samples_per_gpu: 4
  workers_per_gpu: 4
  drop_last: false
  pin_memory: true

  train:
    name: &DATASET_TYPE MTRDataset
    data_root: &DATA_ROOT data/
    scenario_dir: processed_scenarios_training
    ann_file: processed_scenarios_training_infos.pkl
    agent_types:
      &AGENT_TYPES ["TYPE_VEHICLE", "TYPE_PEDESTRIAN", "TYPE_CYCLIST"]
    transforms:
      - name: FilterScenario
        filters:
          - name: FilterScenarioByType
          - name: FilterScenarioByPastMask
      - name: MtrAgentEmbed
        with_velocity: &WITH_VELOCITY true
      - name: MtrPolylineEmbed
        num_polylines: &NUM_POLYLINES 768
        num_points: &NUM_POINTS 20
        break_distance: &BREAK_DISTANCE 1.0
        center_offset: &MAP_CENTER_OFFSET [30.0, 0.0]
      - name: LoadFutureAnnotation
      - name: LoadIntentionPoint
        filepath: &INTENTION_POINT_FILE ./projects/
    predict_all_agents: &PREDICT_ALL_AGENTS false

  test:
    name: *DATASET_TYPE
    data_root: *DATA_ROOT
    scenario_dir: processed_scenarios_validation
    ann_file: processed_scenarios_val_infos.pkl
    agent_types: *AGENT_TYPES
    transforms:
      - name: FilterScenario
        filters:
          - name: FilterScenarioByType
          - name: FilterScenarioByPastMask
      - name: MtrAgentEmbed
        with_velocity: *WITH_VELOCITY
      - name: MtrPolylineEmbed
        num_polylines: *NUM_POLYLINES
        num_points: *NUM_POINTS
        break_distance: *BREAK_DISTANCE
        center_offset: *MAP_CENTER_OFFSET
      - name: LoadFutureAnnotation
      - name: LoadIntentionPoint
        filepath: *INTENTION_POINT_FILE
    predict_all_agents: *PREDICT_ALL_AGENTS

model:
  name: MTR

  encoder:
    name: MTREncoder

    agent_polyline_encoder:
      name: PointNetPolylineEncoder
      in_channels: 30 # NUM_INPUT_ATTR_AGENT + 1
      hidden_dim: 256 # NUM_CHANNEL_IN_MLP_AGENT
      num_layers: 3 # NUM_LAYER_IN_MLP_AGENT
      out_channels: &D_MODEL 256 # D_MODEL

    map_polyline_encoder:
      name: PointNetPolylineEncoder
      in_channels: 9 # NUM_INPUT_ATTR_MAP
      hidden_dim: 64 # NUM_CHANNEL_IN_MLP_MAP
      num_layers: 5 # NUM_LAYER_IN_MLP_MAP
      num_pre_layers: 3 # NUM_LAYER_IN_PRE_MLP_NAP
      out_channels: *D_MODEL # D_MODEL

    attention_layer:
      name: TransformerEncoderLayer
      d_model: *D_MODEL # D_MODEL
      num_head: 8 # NUM_ATTN_HEAD
      dim_feedforward: 1024 # D_MODEL * 4
      dropout: 0.1 # DROPOUT_OF_ATTN: 0.1
      normalize_before: false
      use_local_attn: true
      num_layers: 6 # NUM_ATTN_LAYERS

    num_attn_neighbors: 16
    use_local_attn: true

  decoder:
    name: MTRDecoder

    in_channels: *D_MODEL
    num_future_frames: 80 # NUM_FUTURE_FRAMES
    num_motion_modes: 6 # NUM_MOTION_MODES
    d_model: 512 # D_MODEL
    num_decoder_layers: 6 # NUM_DECODER_LAYERS
    num_attn_head: 8 # NUM_ATTN_HEAD
    map_center_offset: *MAP_CENTER_OFFSET
    num_waypoint_map_polylines: 128 # NUM_WAYPOINT_MAP_POLYLINES
    num_base_map_polylines: 256 # NUM_BASE_MAP_POLYLINES
    dropout: 0.1 # DROPOUT_OF_ATTN
    map_d_model: 256 # MAP_D_MODEL
    nms_threshold: 2.5 # NMS_DIST_THRESH
    decode_loss:
      name: MTRLoss
      reg_cfg:
        name: GMMLoss
        weight: 1.0
        use_square_gmm: false
      cls_cfg:
        name: CrossEntropyLoss
        weight: 1.0
      vel_cfg:
        name: L1Loss
        weight: 0.2

optimizer:
  name: AdamW
  lr: 0.0001
  weight_decay: 0.01

lr_scheduler:
  name: LambdaLR
  milestones: [22, 24, 26, 28]
  lr_decay: 0.5
  lr_clip: 0.000001
