/**:
  ros__parameters:
    num_timestamp: 11 # the number of past frames
    timestamp_threshold: 10000.0 # [ms]
    score_threshold: 0.0 # threshold of predicted score
    # labels: ["VEHICLE", "PEDESTRIAN", "CYCLIST"]
    labels: ["VEHICLE"]

    # labels: ["VEHICLE", "PEDESTRIAN", "MOTORCYCLIST", "CYCLIST", "BUS"]
    checkpoint_path: "$(var data_path)/mtr_best.pth"
    model_config: "$(find-pkg-share autoware_mtr_python)/config/mtr_waymo.yaml"
    deploy_config: "$(find-pkg-share autoware_mtr_python)/config/mtr_static.yaml"
    lanelet_file: "$(find-pkg-share autoware_mtr_python)/config/odaiba.lanelet2_map.osm"
    intention_point_file: "$(find-pkg-share autoware_mtr_python)/data/cluster64_dict.pkl"
    onnx_file: "$(find-pkg-share autoware_mtr_python)/data/mtr1x1.onnx"
    custom_ops: [ "$(find-pkg-share autoware_mtr_python)/data/cuda_ops.cpython-310-x86_64-linux-gnu.so"]

